UPDATE Dest_Loc Set Frm_Ret_Cd = Null,Frm_Ret_Msg = Null,	Frm_Beg_Ts = Null,Frm_End_Ts = Null,Frm_File_Sz = Null,Frm_Checksum = Null,To_Ret_Cd  = Null,TO_RET_MSG  = Null,TO_BEG_TS = Null,TO_END_TS = Null, TO_FILE_SZ = null, TO_CHECKSUM = null, SB_FRMT_CD = null,  PROCESS_FLAG = 'N' WHERE Process_Flag = 'Y';
Commit;
  
  



-- ORACLE
DROP TABLE DEST_LOC;
CREATE TABLE DEST_LOC ( 
	PHYS_FILE_ID 	VARCHAR2(14) 	NOT NULL,	
	SCHEMA_NM 		VARCHAR2(10) 	DEFAULT '' NOT NULL, 
	BATCH_ID 		INTEGER 	DEFAULT 0 NOT NULL, 
	PROCESS_FLAG 	CHAR(1) 	DEFAULT 'N' NOT NULL, 
	ACTION_FLAG		CHAR(1) 	NOT NULL, 
	FRM_DEST_ID 	VARCHAR2(12) 	NOT NULL, 
	FRM_LOC 		VARCHAR2(128) 	NOT NULL, 
	TO_DEST_ID 		VARCHAR2(12)	DEFAULT NULL, 
	TO_LOC 			VARCHAR2(128)	DEFAULT NULL, 
	FRM_BEG_TS 		TIMESTAMP 	DEFAULT NULL, 
	FRM_RET_CD		INTEGER 	DEFAULT NULL, 
	FRM_RET_MSG 	VARCHAR2(128) 	DEFAULT NULL, 
	FRM_END_TS		TIMESTAMP 	DEFAULT NULL, 
	FRM_FILE_SZ		INTEGER 	DEFAULT NULL, 
	FRM_CHECKSUM 	VARCHAR2(128) 	DEFAULT NULL,
	TO_BEG_TS		TIMESTAMP 	DEFAULT NULL, 
	TO_RET_CD 		INTEGER 	DEFAULT NULL, 
	TO_RET_MSG  	VARCHAR2(128) 	DEFAULT NULL, 
	TO_END_TS		TIMESTAMP 	DEFAULT NULL, 
	TO_FILE_SZ		INTEGER 	DEFAULT NULL, 
	TO_CHECKSUM 	VARCHAR2(128) 	DEFAULT NULL,
	SB_FRMT_CD		INTEGER		DEFAULT NULL,
	CONSTRAINT PK_DEST_LOC PRIMARY KEY( PHYS_FILE_ID ) ) ;
	
insert into dt40903.dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC) values('schema', 1, 'N', 'V', '00001', 'dest_1', 'tst1.tif');
insert into dt40903.dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC) values('schema', 1, 'N', 'D', '00002', 'dest_1', 'DelTest\del1.tif');
insert into dt40903.dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC, TO_LOC) values('schema', 1, 'N', 'R', '00003', 'dest_1', 'tst1.tif','D:/AFTGETS/AFT_IMAGES/RetrvTest/tst1.tif');
insert into dt40903.dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC, TO_LOC) values('schema', 1, 'N', 'S', '00004', 'dest_1', 'D:\AFTGETS\AFT_IMAGES\tst1.tif','StoreTest/tst1.tif');



DROP TABLE DT40903.DEST_LOC;
CREATE TABLE DT40903.DEST_LOC ( 
	SCHEMA_NM 		CHAR(10) 	NOT NULL DEFAULT '' , 
	BATCH_ID 		INTEGER 	NOT NULL DEFAULT 0, 
	PROCESS_FLAG 	CHAR(1) 	NOT NULL DEFAULT 'N' , 
	ACTION_FLAG		CHAR(1) 	NOT NULL, 
	PHYS_FILE_ID 	CHAR(14) 	NOT NULL, 
	FRM_DEST_ID 	CHAR(12) 	NOT NULL, 
	FRM_LOC 		CHAR(128) 	NOT NULL, 
	TO_DEST_ID 		CHAR(12)	DEFAULT NULL, 
	TO_LOC 			CHAR(128)	DEFAULT NULL, 
	FRM_BEG_TS 		TIMESTAMP 	DEFAULT NULL, 
	FRM_RET_CD		INTEGER 	DEFAULT NULL, 
	FRM_RET_MSG 	CHAR(128) 	DEFAULT NULL, 
	FRM_END_TS		TIMESTAMP 	DEFAULT NULL, 
	FRM_FILE_SZ		INTEGER 	DEFAULT NULL, 
	FRM_CHECKSUM 	CHAR(128) 	DEFAULT NULL,
	TO_BEG_TS		TIMESTAMP 	DEFAULT NULL, 
	TO_RET_CD 		INTEGER 	DEFAULT NULL, 
	TO_RET_MSG  	CHAR(128) 	DEFAULT NULL, 
	TO_END_TS		TIMESTAMP 	DEFAULT NULL, 
	TO_FILE_SZ		INTEGER 	DEFAULT NULL, 
	TO_CHECKSUM 	CHAR(128) 	DEFAULT NULL,
	SB_FRMT_CD		INTEGER		DEFAULT NULL,
	CONSTRAINT DT40903.PK_DEST_LOC PRIMARY KEY( PHYS_FILE_ID ) ) ;
	

insert into dt40903.dest_loc(SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC, TO_DEST_ID, TO_LOC) values('schema', 1, 'N', 'm', '00005', '1', 'images\batch1\tst1.tif','2','StoreTest/migrated.tif');
	
	
insert into dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC) values('schema', 1, 'N', 'V', '00001', 'dest_1', 'tst1.tif');
insert into dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC) values('schema', 1, 'N', 'D', '00002', 'dest_1', 'DelTest\del1.tif');
insert into dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC, TO_LOC) values('schema', 1, 'N', 'R', '00003', 'dest_1', 'tst1.tif','D:/AFTGETS/AFT_IMAGES/RetrvTest/tst1.tif');
insert into dest_loc (SCHEMA_NM, BATCH_ID,	PROCESS_FLAG, ACTION_FLAG,PHYS_FILE_ID, FRM_DEST_ID, FRM_LOC, TO_LOC) values('schema', 1, 'N', 'S', '00004', 'dest_1', 'D:\AFTGETS\AFT_IMAGES\tst1.tif','StoreTest/tst1.tif');
Insert Into Dest_Loc (Schema_Nm, Batch_Id,	Process_Flag, Action_Flag,Phys_File_Id, Frm_Dest_Id, Frm_Loc, To_Dest_Id, To_Loc) Values('schema', 1, 'N', 'm', '00005', '1', 'images\batch1\tst1.tif','2','StoreTest/migrated.tif');
commit;

drop PROCEDURE DT40903.SPGETDESTLOC_AFT;
CREATE PROCEDURE DT40903.SPGETDESTLOC_AFT( 
	IN P_SCHEMA CHAR(10) , 
	IN P_BATCH_ID INTEGER,
	IN P_PROC_FLAG CHAR(1),
	IN P_LST_PHYSFILE_ID CHAR(14) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	BEGIN 
	 
	DECLARE C_DESTLOC_1 CURSOR WITH RETURN FOR 
	SELECT
		trim(dl.SCHEMA_NM) as SCHEMA_NM,
		trim(dl.BATCH_ID) as BATCH_ID,
		trim(dl.PROCESS_FLAG) as PROCESS_FLAG,
		trim(dl.ACTION_FLAG) as ACTION_FLAG,
		trim(dl.PHYS_FILE_ID) as PHYS_FILE_ID,
		trim(dl.FRM_DEST_ID) as FRM_DEST_ID,
		trim(dl.FRM_LOC) as FRM_LOC,
		trim(dl.TO_DEST_ID) as TO_DEST_ID,
		trim(dl.TO_LOC) as TO_LOC
	FROM 
		DT40903.DEST_LOC dl
	WHERE 
		dl.SCHEMA_NM = P_SCHEMA 
	 	AND dl.BATCH_ID = P_BATCH_ID 
	 	AND dl.PROCESS_FLAG = P_PROC_FLAG 
	 ORDER BY PHYS_FILE_ID ASC 
	FETCH FIRST 5000 ROWS ONLY FOR READ ONLY WITH UR; 
  
	DECLARE C_DESTLOC_2 CURSOR WITH RETURN FOR 
	SELECT
		trim(dl.SCHEMA_NM) as SCHEMA_NM,
		trim(dl.BATCH_ID) as BATCH_ID,
		trim(dl.PROCESS_FLAG) as PROCESS_FLAG,
		trim(dl.ACTION_FLAG) as ACTION_FLAG,
		trim(dl.PHYS_FILE_ID) as PHYS_FILE_ID,
		trim(dl.FRM_DEST_ID) as FRM_DEST_ID,
		trim(dl.FRM_LOC) as FRM_LOC,
		trim(dl.TO_DEST_ID) as TO_DEST_ID,
		trim(dl.TO_LOC) as TO_LOC
	FROM 
		DT40903.DEST_LOC dl
	WHERE 
		dl.SCHEMA_NM = P_SCHEMA 
	 	AND dl.BATCH_ID = P_BATCH_ID 
	 	AND dl.PROCESS_FLAG = P_PROC_FLAG  
	 	AND PHYS_FILE_ID > P_LST_PHYSFILE_ID 
	 ORDER BY PHYS_FILE_ID ASC 
	FETCH FIRST 5000 ROWS ONLY FOR READ ONLY WITH UR; 
	 
	IF ( P_LST_PHYSFILE_ID IS NULL ) THEN 
		OPEN C_DESTLOC_1; 
	ELSE	 
		OPEN C_DESTLOC_2; 
	END IF ; 
END  ; 
  
COMMENT ON PARAMETER SPECIFIC PROCEDURE DT40903.SPGETDESTLOC_AFT 
( 
	P_SCHEMA IS 'SCHEMA of DEST_LOC', 
	P_BATCH_ID IS 'BATCH of DEST_LOC',
	P_PROC_FLAG IS ' PROCESS FLAG VALUE',
	P_LST_PHYSFILE_ID IS 'Last PHYS_FILE_ID Processed'
) ;

/* Creating index JHLIFE.DEST_LOC_IDX03
When creating this index the database connection should have a sort sequence of *HEX. */
CREATE INDEX JHLIFE.DEST_LOC_IDX03 ON JHLIFE.DEST_LOC (SCHEMA_NM  ASC, BATCH_ID  ASC, PROCESS_FLAG  ASC);


drop PROCEDURE DT40903.SPGET_DESTINCT_DESTIDS;
CREATE PROCEDURE DT40903.SPGET_DESTINCT_DESTIDS( ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	BEGIN 
	 
	DECLARE C_DESTID CURSOR WITH RETURN FOR 
	WITH FIND_DEST as
	(
		SELECT 
			COUNT(*),FRM_DEST_ID AS DESTID 
		FROM 
			DT40903.DEST_LOC 
		GROUP BY FRM_DEST_ID 
		UNION ALL
		SELECT 
			COUNT(*),TO_DEST_ID AS DESTID 
		FROM 
			DT40903.DEST_LOC 
		WHERE 
			TO_DEST_ID IS NOT NULL 
		GROUP BY TO_DEST_ID 
	)
	SELECT DISTINCT TRIM(DESTID) AS DEST_ID FROM FIND_DEST FOR READ ONLY WITH UR;
	
	OPEN C_DESTID; 
	 
END; 

drop PROCEDURE DT40903.SP_UPD_DESTLOC_V;
CREATE PROCEDURE DT40903.SP_UPD_DESTLOC_V( 
	IN P_PHYS_FILE_ID CHAR(14), 
	IN P_FRM_RET_CD INTEGER,
	IN P_FRM_RET_MSG CHAR(128),
	IN P_FRM_BEG_TS TIMESTAMP,
	IN P_FRM_END_TS TIMESTAMP,
	IN P_TO_BEG_TS TIMESTAMP,
	IN P_TO_END_TS TIMESTAMP) 
	LANGUAGE SQL 
	BEGIN 
	UPDATE
		DT40903.DEST_LOC
	SET
		FRM_RET_CD = P_FRM_RET_CD,
		FRM_RET_MSG = P_FRM_RET_MSG,
		FRM_BEG_TS = P_FRM_BEG_TS,
		FRM_END_TS = P_FRM_END_TS,
		TO_BEG_TS = P_TO_BEG_TS,
		TO_END_TS = P_TO_END_TS,
		PROCESS_FLAG = 'Y'
	WHERE
		PHYS_FILE_ID = P_PHYS_FILE_ID;
	
END  ; 
  
COMMENT ON PARAMETER SPECIFIC PROCEDURE DT40903.SP_UPD_DESTLOC_V 
( 
	P_PHYS_FILE_ID 	IS 'PHYS_FILE_ID', 
	P_FRM_RET_CD 	IS 'FROM RETURN CODE',
	P_FRM_RET_MSG 	IS 'FROM RETURN MESSAGE',
	P_FRM_BEG_TS 	IS 'FROM BEGIN TIMESTAMP',
	P_FRM_END_TS 	IS 'FROM END TIMESTAMP',
	P_TO_BEG_TS 	IS 'TO BEGIN TIMESTAMP',
	P_TO_END_TS 	IS 'TO END TIMESTAMP'
	
) ;
update 
	DT40903.DEST_LOC 
set 
	FRM_BEG_TS=NULL, 
	FRM_RET_CD=NULL, 
	FRM_RET_MSG=NULL, 
	FRM_END_TS=NULL, 
	FRM_BYTE_CT=NULL, 
	FRM_CHECKSUM=NULL, 
	TO_BEG_TS=NULL, 
	TO_RET_CD=NULL, 
	TO_RET_MSG=NULL, 
	TO_END_TS=NULL, 
	TO_BYTE_CT=NULL, 
	TO_CHECKSUM=NULL,
	PROCESS_FLAG = 'N'
WHERE 
	PROCESS_FLAG = 'Y';


CALL DT40903.SP_UPD_DESTLOC_V('00001         ',0,'Exists', current timestamp,current timestamp,current timestamp,current timestamp );